"use client";
import { useEffect, useRef, useState } from "react";
interface Step { text: string; metric?: string; }
interface Job { company: string; role: string; period: string; status: "current" | "past"; steps: Step[]; }
const jobs: Job[] = [
{company:"Cognizant",role:"Data Engineer · Education / University Assessment",period:"March 2025 — Present",status:"current",steps:[
{text:"Designed end-to-end ETL pipelines with Airflow, PySpark and Cloudera, ingesting multi-source data into Hive & Impala on AWS S3.",metric:"100% report coverage"},{text:"Engineered 20+ Spark SQL workflows over exam and marking records using Hive, S3 and Iceberg.",metric:"20+ workflows"},{text:"Built scalable data models and quality controls across examination records spanning multiple domains.",metric:"75k+ records"},{text:"Delivered the Report Maker project — Airflow-orchestrated ingestion feeding self-serve performance dashboards.",metric:"−85% report time"},{text:"Identified and created missing tables during a critical migration, cutting data loss during cutover.",metric:"−70% data loss"},{text:"Converted complex SQL into optimized PySpark, speeding up execution on large datasets.",metric:"+40% query speed"},{text:"Monitored workflows with CloudWatch, Hue and Cloudera Manager, resolving bottlenecks proactively.",metric:"+30% reliability"}]},
{company:"Infosys",role:"Data Engineer · Football Streaming",period:"September 2021 — February 2025",status:"past",steps:[{text:"Built a real-time streaming pipeline for football match data using RabbitMQ, Kafka, Apache Flink and Azure EventHub."},{text:"Engineered a timestamp feature for precise tracking and synchronization in the streaming process.",metric:"+20% processing"},{text:"Deployed and managed JAR builds via Azure Blob Storage into Ververica."},{text:"Managed streaming data for 5 major leagues across 10 production and non-production setups.",metric:"5 leagues"},{text:"Configured Apache Kafka streams for high-throughput real-time ingestion.",metric:"100k+ msgs/min"},{text:"Wrote automated data-validation scripts in Python, cutting manual verification effort.",metric:"−80% manual effort"},{text:"Documented 20+ pipeline workflows and data lineage in Confluence and Jira."}]}
];
function JobBlock({job,active}:{job:Job;active:boolean}){return <div className={`experience-job ${active?"experience-live":""}`}><div className="flex items-baseline justify-between gap-4"><h3 className="font-display text-lg font-medium text-ink">{job.company}</h3><span className="whitespace-nowrap text-[12px] text-muted">{job.period}</span></div><p className="mt-1 text-[13px] text-muted">{job.role}</p><ul className="dag-list mt-6 space-y-4">{job.steps.map((step,i)=><li key={i} className="dag-task flex gap-4 text-[14px] leading-relaxed text-muted" style={{transitionDelay:`${i*100}ms`}}><span className="dag-status mt-[2px] shrink-0 font-mono text-[11px]">{active?"✓":String(i+1).padStart(2,"0")}</span><p>{step.text}{step.metric&&<span className="metric-output ml-1.5" style={{color:"var(--accent)"}}>— {step.metric}</span>}</p></li>)}</ul></div>}
export default function Experience(){const [visible,setVisible]=useState(false);const ref=useRef<HTMLElement>(null);useEffect(()=>{if(!ref.current)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setVisible(true);o.disconnect();}},{threshold:.18});o.observe(ref.current);return()=>o.disconnect();},[]);return <section ref={ref} id="pipeline" className="border-t border-line"><div className="mx-auto max-w-content px-6 py-20 md:px-8"><p className="font-display text-[15px] italic text-muted">Experience</p><h2 className="mt-3 max-w-lg font-display text-2xl font-medium leading-snug tracking-tight text-ink">Two roles, read the way I&apos;d document a DAG</h2><div className="mt-14 grid gap-14 lg:grid-cols-2 lg:gap-20">{jobs.map((job,i)=><JobBlock key={job.company} job={job} active={visible}/>)}</div></div></section>}
