"use client";
import {useEffect,useRef,useState} from "react";
import {Play,Volume2,VolumeX} from "lucide-react";
import DataScene from "./DataScene";
const TARGET=75342;
function Metric({target,suffix="",prefix=""}:{target:number;suffix?:string;prefix?:string}){const[v,setV]=useState(0);useEffect(()=>{let n=0;const t=setInterval(()=>{n++;setV(n<15?Math.max(0,Math.round(target*n/15+(Math.random()-.5)*target*.13)):target);if(n>=15)clearInterval(t)},55);return()=>clearInterval(t)},[target]);return <>{prefix}{v.toLocaleString()}{suffix}</>}
export default function Hero(){const[running,setRunning]=useState(false),[runKey,setRunKey]=useState(0),[dag,setDag]=useState(-1),[dagVisible,setDagVisible]=useState(false),[counter,setCounter]=useState(0),[success,setSuccess]=useState(false),[muted,setMuted]=useState(false);const timers=useRef<ReturnType<typeof setTimeout>[]>([]),audio=useRef<AudioContext|null>(null);useEffect(()=>()=>timers.current.forEach(clearTimeout),[]);
const tone=(f:number,d=.07,delay=0,type:OscillatorType="sine",gain=.022)=>{if(muted||typeof window==="undefined")return;const C=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!C)return;if(!audio.current)audio.current=new C();const c=audio.current,o=c.createOscillator(),g=c.createGain(),s=c.currentTime+delay;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(gain,s+.008);g.gain.exponentialRampToValueAtTime(.0001,s+d);o.connect(g);g.connect(c.destination);o.start(s);o.stop(s+d+.02)};
const run=()=>{if(running)return;timers.current.forEach(clearTimeout);timers.current=[];setRunKey(k=>k+1);setRunning(true);setSuccess(false);setCounter(0);setDag(-1);setDagVisible(false);tone(180,.12);tone(270,.1,.08);timers.current.push(setTimeout(()=>setDagVisible(true),1250));[0,1,2,3].forEach(i=>timers.current.push(setTimeout(()=>{setDag(i);tone(500+i*85,.06,0,"square",.012)},1550+i*650)));for(let i=1;i<=30;i++)timers.current.push(setTimeout(()=>setCounter(Math.round(TARGET*i/30)),3800+i*40));timers.current.push(setTimeout(()=>{setDag(4);setCounter(TARGET);setRunning(false);setSuccess(true);tone(660,.12);tone(880,.18,.09);timers.current.push(setTimeout(()=>setSuccess(false),4500))},5100))};
return <section id="top" className="relative overflow-hidden"><div className="mx-auto max-w-content px-6 pb-16 pt-20 md:px-8 md:pb-24 md:pt-28"><div className="hero-grid"><div className="hero-copy"><p className="hero-reveal hero-reveal-1 font-display text-[15px] italic text-muted">Data engineer — Kerala, India</p><h1 className="hero-reveal hero-reveal-2 mt-5 max-w-2xl font-display text-[2.75rem] font-medium leading-[1.12] tracking-tight text-ink md:text-6xl">I turn scattered data into pipelines people can rely on.</h1><p className="hero-reveal hero-reveal-3 mt-6 max-w-md text-[15px] leading-relaxed text-muted">Airflow, Spark, Kafka and AWS — building the systems that move data from messy and multi-sourced to trusted and queryable.</p><div className="hero-reveal hero-reveal-4 mt-8 flex flex-wrap items-center gap-6"><a href="#pipeline" className="focus-ring rounded-full px-5 py-2.5 text-[14px] font-medium text-bg" style={{backgroundColor:"var(--accent)"}}>View experience</a><a href="#contact" className="focus-ring text-[14px] font-medium text-ink underline decoration-line underline-offset-4">Get in touch</a></div></div><div className="hero-reveal hero-reveal-3d relative min-h-[360px]"><DataScene runKey={runKey} running={running}/><div className="scene-label label-source">SOURCES</div><div className="scene-label label-s3">S3 LAKE</div><div className="scene-label label-airflow">AIRFLOW</div><div className="scene-label label-spark">PYSPARK</div><div className="scene-label label-report">REPORTS</div></div></div>
<div className="pipeline-console hero-reveal hero-reveal-5 relative mt-7 min-h-[118px] border-y border-line py-4"><div className="flex items-center justify-between gap-3"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-muted">live pipeline control</div><div className="flex gap-2"><button onClick={()=>setMuted(v=>!v)} className="focus-ring rounded-full border border-line p-2 text-muted" aria-label="Toggle sound">{muted?<VolumeX size={13}/>:<Volume2 size={13}/>}</button><button onClick={run} disabled={running} className="focus-ring flex items-center gap-1.5 rounded-full border border-line px-3 py-1.5 text-[12px] text-muted disabled:opacity-60"><Play size={11}/>{running?"Running…":"Run pipeline"}</button></div></div>
{dagVisible&&<div className="persistent-dag mt-4"><span className="dag-caption">Airflow DAG</span>{["ingest","validate","transform","load"].map((x,i)=><div key={x} className={`persistent-task ${dag===i?"processing":dag>i?"done":"waiting"}`}><b>{dag>i?"✓":dag===i?"◉":"○"}</b><span>{x}</span>{i<3&&<em>→</em>}</div>)}</div>}
<div className="mt-3 font-mono text-[11px] text-muted">{running?<>{counter.toLocaleString()} records processed <span className="terminal-caret">▌</span></>:success?<span style={{color:"var(--accent)"}}>✓ pipeline succeeded — {TARGET.toLocaleString()} records</span>:dagVisible&&dag>=4?<span style={{color:"var(--accent)"}}>✓ DAG complete · ready for next run</span>:"Click Run pipeline to execute the 3D environment"}</div></div>
<div className="hero-reveal hero-reveal-6 mt-6 grid grid-cols-3 divide-x divide-line"><div className="pr-4"><p className="font-display text-xl font-medium"><Metric target={100} suffix="k+"/></p><p className="text-[12px] text-muted">messages / min</p></div><div className="px-4"><p className="font-display text-xl font-medium"><Metric target={75} suffix="k+"/></p><p className="text-[12px] text-muted">records per run</p></div><div className="pl-4"><p className="font-display text-xl font-medium"><Metric target={85} prefix="−" suffix="%"/></p><p className="text-[12px] text-muted">report turnaround</p></div></div></div></section>}
